# Generated by Django 4.2.27 on 2025-12-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurtka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=250)),
                ('brend', models.CharField(max_length=250)),
                ('rang', models.CharField(max_length=250)),
                ('narx', models.IntegerField()),
                ('rasm', models.ImageField(upload_to='media/')),
                ('skidka', models.IntegerField()),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
