# Generated by Django 4.2.27 on 2025-12-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiyimlar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurtka',
            old_name='rasm',
            new_name='image',
        ),
    ]
