# Generated by Django 4.2.27 on 2025-12-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiyimlar', '0002_rename_rasm_kurtka_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='futbolka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
                ('cost', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
                ('image2', models.ImageField(upload_to='products/')),
                ('coutry', models.CharField(max_length=255)),
                ('we_have', models.IntegerField()),
                ('datatime', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parant_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kiyimlar.futbolka')),
            ],
        ),
    ]
