# Generated by Django 4.2.27 on 2025-12-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiyimlar', '0003_futbolka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product/')),
                ('color', models.CharField(choices=[('qora', 'Qora'), ('oq', 'Oq'), ('qizil', 'Qizil')], max_length=30)),
                ('brend', models.CharField(choices=[('samsung', 'Samsung'), ('iphone', 'Iphone')], max_length=30)),
                ('ram', models.CharField(choices=[('gb4', '4 gb'), ('gb8', '8 gb')], max_length=30)),
            ],
        ),
    ]
